# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Person',
            new_name='user',
        ),
    ]
