# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170624_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='skills',
            field=models.ManyToManyField(to='main.Skill'),
        ),
    ]
